version: '3.4'

volumes:
  pg_data:
    driver: local

services:
  client:
    build:
      context: client
      target: dev
    environment:
      - PORT=3000
      - VITE_SERVER_HOST=http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
  server:
    depends_on:
      database:
        condition: service_healthy
    build: server
    environment:
      - PORT=3001
      - DATABASE_NAME=testdb
      - DATABASE_HOST=database
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./server/src:/app/src
  database:
    image: postgres:15.1
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
      - "172.17.0.1:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
