FROM node:16

WORKDIR /app
COPY . .

RUN ["npm", "install"]
CMD ["npm", "run", "serve"]
# Base node image

# Legge inn dependencies man trenger fra distro

# Legge inn dependencies man trenger fra prosjektet

# Kopiere over kildekode

# Eksponere port
# Bygge til produksjon

# Nytt base image med webserver

# Kopiere inn nginx config

# Kopiere over bygde filer

# Noe slags environment for å styre ting?

# Entrypoint/cmd for å kjøre webserveren
